[package]
name = "neuron_script_api_procmacro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.101"
quote = "1.0.40"
proc-macro2 = "1.0.95"
darling = "0.20.11"
proc-macro-crate = "3.3.0"